apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: milks.uknbr.io
spec:
  scope: Namespaced
  group: uknbr.io
  versions:
    - name: v1
      served: true
      storage: true
  names:
    kind: Milk
    plural: milks
    singular: milk
    shortNames:
      - mlk
  additionalPrinterColumns:
    - name: Replicas
      type: integer
      priority: 0
      JSONPath: .spec.replicas
      description: Number of replicas
    - name: URL
      type: string
      priority: 0
      JSONPath: .spec.url
      description: Milk image URL