apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: indicatorpods.uknbr.io
spec:
  scope: Namespaced
  group: uknbr.io
  versions:
    - name: v1
      served: true
      storage: true
  names:
    kind: IndicatorPod
    plural: indicatorpods
    singular: indicatorpod
    shortNames:
      - inp
  additionalPrinterColumns:
    - name: Restarts
      type: integer
      priority: 0
      JSONPath: .spec.restarts
      description: Limit of restarts
    - name: Label
      type: string
      priority: 0
      JSONPath: .spec.label
      description: Label to indicate problematic pod